export const initialValuesBilling = {
  firstName: {
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 20,
    helperText: "Please enter First Name",
  },
  lastName: {
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 20,
    helperText: "Please enter Last Name",
  },
  address: {
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 50,
    helperText: "Please enter valid address",
  },
  address2: {
    value: "",
    error: "",
    required: false,
    validate: "text",
    minLength: 2,
    maxLength: 50,
    helperText: "",
  },
  city: {
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 25,
    helperText: "Please enter valid city",
  },
  userState: {
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 25,
    helperText: "Please enter valid state",
  },
  country: {
    value: "",
    error: "",
    required: true,
    validate: "select",
    helperText: "Please select valid country",
  },
  postalcode: {
    value: "",
    error: "",
    required: true,
    validate: "number",
    maxLength: 6,
    helperText: "Please enter valid postal code",
  },
  phone: {
    value: "",
    error: "",
    required: true,
    validate: "phone",
    maxLength: 10,
    helperText: "Please select valid phone number",
  },
  landMark: {
    value: "",
    error: "",
    required: false,
    validate: "text",
    minLength: 2,
    maxLength: 50,
    helperText: "",
  },
  agreenemt: {
    value: false,
    error: "",
    required: true,
    validate: "checkbox",
    helperText: "Please accept our terms and conditions",
  },
};
